# Generated by Django 6.0.7 on 2026-07-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chantiers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('date_embauche', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'embauche")),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salaire de base')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'En congé'), ('suspendu', 'Suspendu')], default='actif', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='accounts.entreprise', verbose_name='Entreprise')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('chef_equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_gerer', to='rh.employe', verbose_name="Chef d'équipe")),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='accounts.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['entreprise', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'affectation")),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='rh.employe', verbose_name='Employé')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='rh.equipe', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'verbose_name_plural': "Membres d'équipe",
                'unique_together': {('equipe', 'employe')},
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jour', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('conge', 'Congé')], default='present', max_length=20, verbose_name='Statut')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='chantiers.chantier', verbose_name='Chantier')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='rh.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date_jour'],
                'unique_together': {('employe', 'date_jour')},
            },
        ),
    ]
