# Generated by Django 6.0.7 on 2026-07-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chantiers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('date_acquisition', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'acquisition")),
                ('valeur_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Valeur d'achat")),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('affecte', 'Affecté'), ('en_maintenance', 'En maintenance'), ('en_panne', 'En panne'), ('hors_service', 'Hors service')], default='disponible', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='accounts.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['entreprise', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('curative', 'Curative')], default='preventive', max_length=20, verbose_name='Type')),
                ('date_maintenance', models.DateField(default=django.utils.timezone.now, verbose_name='Date de maintenance')),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prochaine_echeance', models.DateField(blank=True, null=True, verbose_name='Prochaine échéance')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='materiels.materiel', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_maintenance'],
            },
        ),
        migrations.CreateModel(
            name='AlerteMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maintenance', 'Maintenance due'), ('panne', 'Panne'), ('hors_service', 'Hors service')], max_length=20, verbose_name='Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_alerte', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'alerte")),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('resolue', 'Résolue')], default='ouverte', max_length=20, verbose_name='Statut')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='materiels.materiel', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Alerte matériel',
                'verbose_name_plural': 'Alertes matériel',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='AffectationMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_materiel', to='chantiers.chantier', verbose_name='Chantier')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='materiels.materiel', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Affectation de matériel',
                'verbose_name_plural': 'Affectations de matériel',
                'ordering': ['-date_debut'],
            },
        ),
    ]
