# Generated by Django 6.0.7 on 2026-07-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_incident', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'incident")),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=20, verbose_name='Gravité')),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('clos', 'Clos')], default='signale', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la phase')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('avancement_pct', models.IntegerField(default=0, verbose_name='Avancement (%)')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('statut', models.CharField(choices=[('non_commencee', 'Non commencée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('bloquee', 'Bloquée')], default='non_commencee', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'ordering': ['chantier', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du chantier')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budget prévu')),
                ('budget_reel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budget réel')),
                ('statut', models.CharField(choices=[('planification', 'Planification'), ('actif', 'Actif'), ('en_pause', 'En pause'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planification', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('chef_chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_chef', to=settings.AUTH_USER_MODEL, verbose_name='Chef de chantier')),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
                'ordering': ['-date_creation'],
            },
        ),
    ]
