# Generated by Django 6.0.7 on 2026-07-29 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chantiers', '0001_initial'),
        ('commercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers', to='commercial.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='chantier',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='accounts.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='incident',
            name='chantier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='chantiers.chantier', verbose_name='Chantier'),
        ),
        migrations.AddField(
            model_name='incident',
            name='declare_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_declares', to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par'),
        ),
        migrations.AddField(
            model_name='phase',
            name='chantier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='chantiers.chantier', verbose_name='Chantier'),
        ),
        migrations.AlterUniqueTogether(
            name='chantier',
            unique_together={('entreprise', 'nom')},
        ),
    ]
