export const ROLE_MODULES: Record<string, string[]> = {
  super_admin: [
    '/super-admin',
    '/super-admin/entreprises',
    '/super-admin/utilisateurs',
    '/super-admin/abonnements',
    '/super-admin/facturation',
    '/super-admin/logs',
    '/super-admin/parametres',
    '/dashboard',
  ],
  admin_entreprise: [
    '/dashboard',
    '/chantiers',
    '/finance',
    '/rh',
    '/materiels',
    '/stocks',
    '/commercial',
    '/alertes',
    '/historique-logins',
    '/settings',
  ],
  directeur: [
    '/dashboard',
    '/chantiers',
    '/finance',
    '/commercial',
    '/rh',
    '/materiels',
    '/stocks',
    '/alertes',
  ],
  comptable: [
    '/dashboard',
    '/finance',
    '/commercial',
    '/chantiers',
    '/rh',
    '/alertes',
  ],
  chef_chantier: [
    '/dashboard',
    '/chantiers',
    '/rh',
    '/materiels',
    '/stocks',
    '/finance',
    '/alertes',
  ],
  chef_projet: [
    '/dashboard',
    '/chantiers',
    '/rh',
    '/materiels',
    '/stocks',
    '/finance',
    '/alertes',
  ],
  rh: [
    '/dashboard',
    '/rh',
    '/chantiers',
    '/alertes',
  ],
  materiel: [
    '/dashboard',
    '/materiels',
    '/chantiers',
    '/alertes',
  ],
  magasinier: [
    '/dashboard',
    '/stocks',
    '/chantiers',
    '/alertes',
  ],
  commercial: [
    '/dashboard',
    '/commercial',
    '/chantiers',
    '/finance',
    '/alertes',
  ],
  employe: [
    '/dashboard',
    '/chantiers',
    '/rh',
    '/materiels',
    '/stocks',
    '/alertes',
  ],
  client: [
    '/dashboard',
    '/commercial',
    '/chantiers',
  ],
}

export const ROLE_NAMES: Record<string, string> = {
  super_admin: 'Super Admin SaaS',
  admin_entreprise: 'Admin Entreprise',
  directeur: 'Direction Générale',
  comptable: 'Comptable',
  chef_chantier: 'Chef de Chantier',
  chef_projet: 'Chef de Projet',
  rh: 'Responsable RH',
  materiel: 'Responsable Matériel',
  magasinier: 'Magasinier',
  commercial: 'Commercial',
  employe: 'Ouvrier / Employé',
  client: 'Client',
}

export const ROLE_DASHBOARD_TITLE: Record<string, string> = {
  super_admin: 'Supervision SaaS & Tenants',
  admin_entreprise: 'Administration & Supervision',
  directeur: 'Pilotage Stratégique',
  comptable: 'Gestion Financière & Comptable',
  chef_chantier: 'Suivi Chantier & Équipe',
  chef_projet: 'Supervision Multi-Projets',
  rh: 'Gestion RH & Pointages',
  materiel: 'Parc Matériel & Maintenance',
  magasinier: 'Stocks & Logistique',
  commercial: 'Performance Commerciale',
  employe: 'Mon Espace Terrain',
  client: 'Espace Client',
}
