# Generated by Django 6.0.7 on 2026-07-28 10:45

import accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'entreprise")),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/', verbose_name='Logo')),
                ('abonnement', models.CharField(choices=[('essai', 'Essai gratuit'), ('standard', 'Standard'), ('premium', 'Premium')], default='essai', max_length=30, verbose_name="Plan d'abonnement")),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('administrateur', 'Administrateur'), ('directeur', 'Directeur'), ('chef_chantier', 'Chef de chantier'), ('comptable', 'Comptable / Gestionnaire'), ('magasinier', 'Magasinier'), ('employe', 'Employé de terrain'), ('client', 'Client')], max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=60, verbose_name='Nom affiché')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos/', verbose_name='Photo de profil')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20, verbose_name='Statut')),
                ('doit_changer_mot_de_passe', models.BooleanField(default=True, verbose_name='Doit changer son mot de passe')),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='accounts.entreprise', verbose_name='Entreprise')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='accounts.role', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', accounts.managers.UtilisateurManager()),
            ],
        ),
    ]
